//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetailsView
    {
        public int BillNo { get; set; }
        public int RetailerId { get; set; }
        public string Name { get; set; }
        public int MaterialId { get; set; }
        public string DisplayName { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DLP { get; set; }
        public decimal Amount { get; set; }
        public string GodownName { get; set; }
        public short GodownId { get; set; }
        public Nullable<byte> GSTApplied { get; set; }
        public int SaleTypeId { get; set; }
        public int SaleCategoryId { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<byte> DiscountApplied { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public Nullable<byte> ShowGSTNo { get; set; }
        public string Contact { get; set; }
        public decimal Rate { get; set; }
        public byte BillStatus { get; set; }
        public System.DateTime SaleDate { get; set; }
        public byte StatusId { get; set; }
    }
}
