//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bill()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int BillNo { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> RetailerId { get; set; }
        public Nullable<int> SaleCategoryId { get; set; }
        public Nullable<int> SaleTypeId { get; set; }
        public Nullable<byte> GSTApplied { get; set; }
        public Nullable<byte> DiscountApplied { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<byte> BillStatus { get; set; }
        public Nullable<decimal> PaidAmt { get; set; }
        public Nullable<decimal> BalanceAmt { get; set; }
        public Nullable<decimal> GSTPercentage { get; set; }
        public Nullable<decimal> GSTAmount { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<byte> ShowGSTNo { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual SupplierRetailer SupplierRetailer { get; set; }
        public virtual SaleCategory SaleCategory { get; set; }
        public virtual SaleType SaleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
