//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentUserRoleRightsView
    {
        public short RightsId { get; set; }
        public string RightsName { get; set; }
        public Nullable<byte> RoleId { get; set; }
        public int HasRights { get; set; }
    }
}
