//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAccount
    {
        public short EmpAccountId { get; set; }
        public short EmployeeNo { get; set; }
        public byte PaymentType { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
    }
}
