//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public string EmployeeName { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<byte> Designation { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Salary { get; set; }
        public string BloodGroup { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<byte> EmploymentType { get; set; }
        public short EmployeeNo { get; set; }
        public string Role { get; set; }
        public Nullable<byte> EmpRoleId { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
    }
}
