//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public int AttendanceId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> EmployeeNo { get; set; }
        public Nullable<byte> Present { get; set; }
        public string Comments { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
