//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInventory
    {
        public int InventoryId { get; set; }
        public int MaterialId { get; set; }
        public short GodownId { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string AddTransfer { get; set; }
        public Nullable<short> TransferToGodown { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<int> OnlinePaymentId { get; set; }
        public Nullable<decimal> QuantityPerUnit { get; set; }
    
        public virtual Godown Godown { get; set; }
        public virtual Godown Godown1 { get; set; }
        public virtual Material Material { get; set; }
        public virtual SupplierRetailer SupplierRetailer { get; set; }
    }
}
