//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialInventory
    {
        public int InventoryId { get; set; }
        public int MaterialId { get; set; }
        public int GodownId { get; set; }
        public int Quantity { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int SupplierId { get; set; }
        public string AddTransfer { get; set; }
        public Nullable<int> TransferToGodown { get; set; }
    }
}
