//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlinePaymentDetail
    {
        public int OnlinePaymentId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string description { get; set; }
        public decimal amount { get; set; }
        public string OnlinePaymentType { get; set; }
        public string Status { get; set; }
        public string InstamojoPaymentId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string currency { get; set; }
        public string TransactionId { get; set; }
        public string RequestId { get; set; }
        public string PaymentStatus { get; set; }
    }
}
