//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReorderRequired
    {
        public int MaterialId { get; set; }
        public string DisplayName { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
        public Nullable<decimal> SoldQuantity { get; set; }
        public Nullable<decimal> TotalIncomingQuantity { get; set; }
        public Nullable<decimal> QIH { get; set; }
        public string InventoryTypeName { get; set; }
    }
}
