//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightsForAssignment
    {
        public short RightsId { get; set; }
        public string RightsName { get; set; }
        public byte RoleId { get; set; }
        public byte Active { get; set; }
        public byte RMActive { get; set; }
        public string RoleName { get; set; }
        public byte RightsManagementId { get; set; }
    }
}
