//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Right
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Right()
        {
            this.RightsManagements = new HashSet<RightsManagement>();
        }
    
        public short RightsId { get; set; }
        public string RightsName { get; set; }
        public byte Active { get; set; }
        public string FeatherName { get; set; }
        public string MenuUrl { get; set; }
        public string DisplayName { get; set; }
        public Nullable<short> PID { get; set; }
        public Nullable<byte> DisplayOrder { get; set; }
        public Nullable<byte> Menu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RightsManagement> RightsManagements { get; set; }
    }
}
