//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightsManagement
    {
        public byte RightsManagementId { get; set; }
        public short RightsId { get; set; }
        public byte RoleId { get; set; }
        public byte Active { get; set; }
    
        public virtual EmployeeRole EmployeeRole { get; set; }
        public virtual Right Right { get; set; }
    }
}
