//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SaleId { get; set; }
        public int MaterialId { get; set; }
        public decimal Rate { get; set; }
        public decimal Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DLP { get; set; }
        public decimal Amount { get; set; }
        public int BillNo { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public short GodownId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public byte Active { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Godown Godown { get; set; }
        public virtual Material Material { get; set; }
    }
}
