//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleQuantityAmountForReport
    {
        public System.DateTime SaleDate { get; set; }
        public string CategoryName { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
